export const PLAYER_POLLING_INTERVAL = 1000;
export const UPNP_FAST_POLLING_INTERVAL = 250;
export const POSITION_UI_TICK_INTERVAL = 50;
export const VOLUME_POLLING_INTERVAL = 1000;
export const POLLING_RESUME_DELAY = 2000;
export const VOLUME_UPDATE_RESET_DELAY = 500;
